<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQAyw0Zu\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQAyw0Zu/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerQAyw0Zu.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerQAyw0Zu\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerQAyw0Zu\appAppKernelProdContainer([
    'container.build_hash' => 'QAyw0Zu',
    'container.build_id' => 'a6aac7dd',
    'container.build_time' => 1715346066,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQAyw0Zu');
