<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMASGJR5\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMASGJR5/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerMASGJR5.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerMASGJR5\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerMASGJR5\appAppKernelProdContainer([
    'container.build_hash' => 'MASGJR5',
    'container.build_id' => '0bbdebe6',
    'container.build_time' => 1714663144,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMASGJR5');
